org: jmarvinh
app: ayllu-api-test-v1
service: ayllu-api-test-v1
plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  region: us-east-1
  runtime: nodejs12.x
  # versionFunctions: false


functions:
  status:
    handler: handlers/status.handler
    events:
      - http:
          method: GET
          path: /status
  #Seed
  seed:
    handler: handlers/seed.handler
    events:
      - http:
          method: GET
          path: /seed
  #Auth
  getAccessToken:
    handler: handlers/auth/getAccessToken.handler
    events:
      - http:
          method: GET
          path: /auth/getAccessToken
  #Users
  getAllUsers:
    handler: handlers/users/getUsers.getAllUsers
    events:
      - http:
          method: GET
          path: /users/getAllUsers
  getUserById:
    handler: handlers/users/getUsers.getUserById
    events:
      - http:
          method: GET
          path: /users/getUserById
  createUser:
    handler: handlers/users/create-user.handler
    events:
      - http:
          method: POST
          path: /users/createUser
  updateUser:
    handler: handlers/users/update-user.handler
    events:
      - http:
          method: POST
          path: /users/updateUser
  assingnProfile:
    handler: handlers/users/assign-profile-user.handler
    events:
      - http:
          method: POST
          path: /users/assignProfile
  authUsers:
    handler: handlers/users/autenticate-user.handler
    events:
      - http:
          method: POST
          path: /users/validarUser
  getPosts:
    handler: handlers/posts.handler
    events:
      - http:
          method: GET
          path: /posts
  #CATEGORY
  getCategories:
    handler: handlers/categories/get-category.handler
    events:
      - http:
          method: GET
          path: /categories
  createCategory:
    handler: handlers/categories/create-category.handler
    events:
      - http:
          method: POST
          path: /categories
  #COURSE  
  getCourseById:
    handler: handlers/courses/get-course.getCourseById
    events:
      - http:
          method: GET
          path: /courses/getById
  getCourseByCategory:
    handler: handlers/courses/get-course.getCourseByCategory
    events:
      - http:
          method: POST
          path: /courses/getByCategory
  getCourseByName:
    handler: handlers/courses/get-course.getCourseByName
    events:
      - http:
          method: POST
          path: /courses/getCourseByName
  getAllCourses:
    handler: handlers/courses/get-course.getAll
    events:
      - http:
          method: GET
          path: /courses
  createCourse:
    handler: handlers/courses/create-course.handler
    events:
      - http:
          method: POST
          path: /courses
  #MODULE 
  getModuleById:
    handler: handlers/modules/get-module.getModuleById
    events:
    - http:
        method: POST
        path: /modules/getById
  getModuleByCourse:
    handler: handlers/modules/get-module.getModuleByCourse
    events:
      - http:
          method: POST
          path: /modules/getByCourse
  createModule:
    handler: handlers/modules/create-module.handler
    events:
      - http:
          method: POST
          path: /modules
  updateModule:
    handler: handlers/modules/updateModule.handler
    events: 
      - http:
          method: POST
          path: /modules/updateModule
  deleteModule:
    handler: handlers/modules/deleteModule.handler
    events:
      - http:
          method: GET
          path: /modules/deleteModule
  #TEST
  getTestByModuleId:
    handler: handlers/tests/getTests.getTestByModuleId
    events: 
      - http:
          method: POST
          path: /tests/getTestByModuleId
  createTest:
    handler: handlers/tests/createTests.handler
    events:
      - http:
          method: POST
          path: /tests/createTest
  updateTest:
    handler: handlers/tests/updateTest.handler
    events:
      - http:
          method: POST
          path: /tests/updateTest
  deleteTest:
    handler: handlers/tests/deleteTest.handler
    events:
      - http:
          method: GET
          path: /tests/deleteTest
  #Questions
  getQuestionsByTest:
    handler: handlers/questions/getQuestions.getQuestionsByTest
    events:
      - http:
          method: POST
          path: /questions/getQuestionsByTest
  getQuestionByOrderId:
    handler: handlers/questions/getQuestions.getQuestionByOrderId
    events:
      - http:
          method: GET
          path: /questions/getQuestionsByOrder
  createQuestion: 
    handler: handlers/questions/createQuestion.handler
    events: 
      - http:
          method: POST
          path: /questions/createQuestion
  updateQuestion:
    handler: handlers/questions/updateQuestion.handler
    events:
      - http:
          method: POST
          path: /questions/updateQuestion
  deleteQuestion:
    handler: handlers/questions/deleteQuestion.handler
    events:
      - http:
          method: GET
          path: /questions/deleteQuestion
  #OPTIONS
  getOptionsByQuestion:
    handler: handlers/options/getOptions.getOptionsByQuestion
    events:
      - http:
          method: POST
          path: /options/getOptionsByQuestion
  createOption:
    handler: handlers/options/createOption.handler
    events:
      - http:
          method: POST
          path: /options/createOption
  updateOption:
    handler: handlers/options/updateOption.handler
    events:
      - http:
          method: POST
          path: /options/updateOption
  deleteOption:
    handler: handlers/options/deleteOption.handler
    events: 
      - http:
          method: GET
          path: /options/deleteOption
  # LESSON
  getLessonById:
    handler: handlers/lessons/get-lesson.getLessonById
    events:
      - http:
          method: POST
          path: /lessons/getById
  getLessonByModule:
    handler: handlers/lessons/get-lesson.getLessonByModule
    events:
      - http:
          method: POST
          path: /lessons/getByModule
  createLesson:
    handler: handlers/lessons/create-lesson.handler
    events:
      - http:
          method: POST
          path: /lessons
  # Resources
  getResourcesByLessonId:
    handler: handlers/resources/get-resource.getResourcesByLessonId
    events:
      - http:
          method: POST
          path: /resources/getResourcesByLessonId
  createResource:
    handler: handlers/resources/create-resource.handler
    events: 
      - http:
          method: POST
          path: /resources
  updateResources:
    handler: handlers/resources/updateResources.handler
    events:
      - http:
          method: POST
          path: /resources/updateResources
  deleteResource:
    handler: handlers/resources/deleteResource.handler
    events:
      - http:
          method: GET
          path: /resources/deleteResource
  #UsersOnCourses 
  getAllUsersOnCourses:
    handler: handlers/usersOnCourses/getUsersOnCourses.getAllUsersOnCourses
    events:
      - http: 
          method: GET
          path: /usersOnCourses
  getUserOnCourseByCourseId:
    handler: handlers/usersOnCourses/getUsersOnCourses.getUserOnCourseByCourseId
    events:
      - http:
          method: GET
          path: /usersOnCourses/getUserOnCourseByCourseId
  getCoursesActive:
    handler: handlers/usersOnCourses/getUsersOnCourses.getCoursesActive
    events:
      - http:
          method: GET
          path: /usersOnCourses/coursesActive
  getCoursesCompleted:
    handler: handlers/usersOnCourses/getUsersOnCourses.getCoursesCompleted
    events:
      - http:
          method: GET
          path: /usersOnCourses/coursesCompleted
  getUserCoursesActive:
    handler: handlers/usersOnCourses/getUsersOnCourses.getUserCoursesActive
    events:
      - http:
          method: GET
          path: /usersOnCourses/userCoursesActive
  getUserCoursesCompleted:
    handler: handlers/usersOnCourses/getUsersOnCourses.getUserCoursesCompleted
    events:
      - http:
          method: GET
          path: /usersOnCourses/userCoursesCompleted
  createUserOnCourse:
    handler: handlers/usersOnCourses/createUserOnCourse.handler
    events:
      - http:
          method: POST
          path: /usersOnCourses
  updateUserOnCourse:
    handler: handlers/usersOnCourses/updateUserOnCourse.handler
    events:
      - http:
          method: POST
          path: /usersOnCourses/update
  deleteUserOnCourse:
    handler: handlers/usersOnCourses/deleteUserOnCourse.handler
    events:
      - http:
          method: GET
          path: /usersOnCourses/delete
  #ModulesOnCourse
  getAllModulesOnCourse:
    handler: handlers/modulesOnCourse/getModulesOnCourse.getAllModulesOnCourse
    events:
      - http:
          method: GET
          path: /modulesOnCourse
  getModuleOnCourseById:
    handler: handlers/modulesOnCourse/getModulesOnCourse.getModuleOnCourseById
    events:
      - http:
          method: POST
          path: /modulesOnCourse/getModuleOnCourseById
  getModulesCompleted:
    handler: handlers/modulesOnCourse/getModulesOnCourse.getModulesCompleted
    events:
      - http:
          method: POST
          path: /modulesOnCourse/modulesCompleted
  createModuleOnCourse:
    handler: handlers/modulesOnCourse/createModuleOnCourse.handler
    events:
      - http:
          method: POST
          path: /modulesOnCourse
  updateModuleOnCouse:
    handler: handlers/modulesOnCourse/updateModuleOnCourse.handler
    events:
      - http:
          method: POST
          path: /modulesOnCourse/update
  getModulesAverageGrade:
    handler: handlers/modulesOnCourse/getModulesOnCourse.getModulesAverageGrade
    events:
      - http:
          method: POST
          path: /modulesOnCourse/getModulesAverageGrade
  #TestAnswers
  getUserTestAnswers:
    handler: handlers/testAnswers/userTestAnswers.getUserTestAnswers
    events:
      - http:
          method: POST
          path: /testAnswers/getUserTestAnswers
  createUserTestAnswers:
    handler: handlers/testAnswers/createUserTestAnswers.handler
    events:
      - http:
          method: POST
          path: /testAnswers/createUserTestAnswers
  updateUserTestAnswers:
    handler: handlers/testAnswers/updateUserTestAnswers.handler
    events:
      - http:
          method: POST
          path: /testAnswers/updateUserTestAnswers
  getTestGrade:
    handler: handlers/testAnswers/userTestAnswers.getTestGrade
    events:
      - http:
          method: POST
          path: /testAnswers/getTestGrade

# only include the Prisma binary required on AWS Lambda while packaging
package:
  patterns:
    - '!node_modules/.prisma/client/libquery_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-rhel-*'
    - '!node_modules/prisma/libquery_engine-*'
    - '!node_modules/@prisma/engines/**'
